### PR TITLE
Add GIMP image editor

### PR DESCRIPTION
**Pull request by EdenSG**
[GIMP](https://www.gimp.org/) is a very powerful open-source image editor.

### CODE REVIEW

**Comment by EdenSG** [comment]
The Travis build failed because https://www.reddit.com/r/Mac returned a 503 when the test was run, just FYI.

**Comment by herrbischoff** [comment]
I would argue that GIMP on Mac OS X is not an Awesome application *at all*. It's clunky and takes forever to start up (during which time it hangs) besides having an abysmal and non-Retina-ready UI with 100% non-native controls. I understand the place GIMP has in the Linux ecosystem but on Mac OS X, it's one of the worst UI/UX I have ever seen.

**Comment by iCHAIT** [comment]
@EdenSG  I agree with @herrbischoff , I installed GIMP a while back and was really disappointed, it lagged a lot and had an ugly UI. Please close.

**Comment by EdenSG** [comment]
Alright, no worries.

**Pull request closed without merging**
