### PR TITLE
Fix Travis Build 

### PR DESCRIPTION
**Pull request by ReadmeCritic**

### CODE REVIEW

**Comment by iCHAIT** [comment]
Why are you removing emacs?

**Comment by ReadmeCritic** [comment]
Project deleted https://github.com/railwaycat/mirror-emacs-mac <- 404
or was it moved?

**Comment by iCHAIT** [comment]
Not sure but still don't remove it can you replace it with - 

- [Emacs](https://www.emacswiki.org/emacs/EmacsForMacOS) - Port of Emacs to work as an OS X.

The link can point to https://www.emacswiki.org/emacs/EmacsForMacOS

**Comment by ReadmeCritic** [comment]
Sorry, will fix!

**Comment by ReadmeCritic** [comment]
@iCHAIT ready for review

**Comment by iCHAIT** [comment]
np, thanks 👍

**Pull request merged**
