### PR TITLE
Add Noizio sound equalizer

### PR DESCRIPTION
**Pull request by forgottenleaf**
Sound equalizer.

### CODE REVIEW

**Comment by forgottenleaf** [comment]
I fixed the failed test in this (due to NepTunes) in PR #258.

**Comment by herrbischoff** [comment]
Duplicate of https://github.com/iCHAIT/awesome-osx/pull/145. Please close.

**Comment by forgottenleaf** [comment]
Shouldn't #145 be closed since it adds more than one app in a pull request?

**Comment by iCHAIT** [comment]
@forgottenleaf Sounds right. No need to close this one.

**Pull request merged**
