### PR TITLE
Added Slack to Communication

### PR DESCRIPTION
**Pull request by oscarmorrison**

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@iCHAIT

**Comment by iCHAIT** [comment]
I don't think this fits the list as it has nothing to do with the Operating System itself.

**Comment by herrbischoff** [comment]
I'm with @iCHAIT. Cross-platform UI apps should generally not be included.

**Comment by oscarmorrison** [comment]
Ok thanks for your consideration @iCHAIT @herrbischoff 
I was under the impression that cross platform was acceptable, as you have plenty in the list already (Source Tree, Text Expander etc)

**Comment by herrbischoff** [comment]
What I mean is cross-platform UI apps. SourceTree, TextExpander and others may be available for Windows as well but are well integrated in the Mac OS look, feel and technology. Applications like Slack are little more than wrappers around a web application. While this is a useful approach for this particular kind of application, it does not exactly stand out as an Awesome application. ;)

**Comment by iCHAIT** [comment]
@oscarmorrison I hope @herrbischoff has explained it pretty well. You may close it :)

**Comment by oscarmorrison** [comment]
Yes thankyou. @iCHAIT @herrbischoff

**Pull request closed without merging**
