### PR TITLE
New resource Bash-it

### PR DESCRIPTION
**Pull request by nucliweb**
Added a new resource in the section **Developers**

### CODE REVIEW

**Comment by iCHAIT** [comment]
Thanks for sharing, a great resource indeed, though I don't think this one suits this particular list, but it is definitely a strong candidate for [awesome-osx-command-line](https://github.com/herrbischoff/awesome-osx-command-line) and [awesome-shell](https://github.com/alebcay/awesome-shell).

**Comment by nucliweb** [comment]
:+1:

**Comment by herrbischoff** [comment]
Thanks for mentioning the repo. Added: https://github.com/herrbischoff/awesome-osx-command-line/commit/484e671feb97a35e518cb72ee4060c76e3c5bca4

**Comment by iCHAIT** [comment]
:+1:

**Pull request closed without merging**
