### PR TITLE
Add »Awesome CLI Apps« to »Command Line Utilities«

### PR DESCRIPTION
**Pull request by mischah**

### CODE REVIEW

**Comment by iCHAIT** [comment]
I am not sure which one should I be merging

https://github.com/iCHAIT/awesome-osx/pull/194/files

:/

@herrbischoff

**Comment by iCHAIT** [comment]
> Search this list before making a new one, as yours may be a duplicate. If it is, try and contribute to the best one instead of making your own.

This is as per the guidelines for [creating your own list](https://github.com/sindresorhus/awesome/blob/master/create-list.md) in the [Awesome List](https://github.com/sindresorhus/awesome).

So I am not sure why do we have 2 similar list, or am I missing something?

**Comment by herrbischoff** [comment]
I created this list very shortly before. Now there is a guy on a mission (not the other lists' owner, mind you) to get an older, but way more fragmented list accepted into Awesome lists. I decided to create my own approach because the existing list would basically need rebuilding from scratch anyway. It's your call. My list was not included in @sindresorhus' in favor of the other, so you decide. You can read up on his disruptive behavior here: https://github.com/sindresorhus/awesome/pull/406

On a side note, having to deal with behavior like that feels like unnecessary friction. Still, in a couple of days no one likely cares.

**Comment by sindresorhus** [comment]
@herrbischoff No one is on a missing here. We're just trying to foster collaboration. If you don't like the way the other list is run you're free to do your own. In the end, I'll pick the best one, even though I've chosen the first one for now.

**Comment by mischah** [comment]
Hej @iCHAIT,
how ever to decide … keep up the good work :octocat:

**Comment by herrbischoff** [comment]
@sindresorhus I'm all for collaboration, just look at my contributions to this list for starters. It's just that dealing with people like mischah is a bit much.

**Comment by iCHAIT** [comment]
I read the thread on the Awesome list @herrbischoff linked me in an earlier comment and I agree with @sindresorhus that there is no clear winner at this point of time, so I am gonna hold both the PR's and reconsider it in the future in the meantime you can work on your lists, and for obvious reasons I would be inclined to go with the list that gets accepted into the Awesome list.

**Comment by mischah** [comment]
> It's just that dealing with people like mischah is a bit much.

**Comment by herrbischoff** [comment]
@iCHAIT, that's a sensible approach. Thanks for weighing in.

**Pull request closed without merging**
