### PR TITLE
Add Quiver app

### PR DESCRIPTION
**Pull request by forgottenleaf**
Notebook for programmers.

### CODE REVIEW

**Comment by forgottenleaf** [comment]
I fixed the failed test in this (due to NepTunes) in PR #258.

**Comment by herrbischoff** [comment]
Duplicate of https://github.com/iCHAIT/awesome-osx/pull/251. Please close.

**Comment by iCHAIT** [comment]
@herrbischoff  On second thoughts I believe #251 should be closed as it has multiple suggestions in a single PR anyway. Merging this.

**Comment by herrbischoff** [comment]
@iCHAIT: Absolutely correct, my bad.

**Pull request merged**
