### PR TITLE
Add Sketch Toolbox to Utilities

### PR DESCRIPTION
**Pull request by brunowego**
:+1:

### CODE REVIEW

**Comment by herrbischoff** [comment]
I'd say this should be listed under "Graphics", next to Sketch itself.

**Comment by brunowego** [comment]
@herrbischoff changed :+1:

**Comment by herrbischoff** [comment]
@brunowego: Looks good! Just one more thing: since it's Open Source, it should carry the OSS logo with a link to the GitHub repository. Please add that as well.

I endorse the addition as it indeed makes adding plugins to Sketch a breeze.

**Comment by herrbischoff** [comment]
Please sort correctly and resolve the conflicts so this can be merged.

**Pull request closed without merging**
