### PR TITLE
Add Tower to `Developers`

### PR DESCRIPTION
**Pull request by sergiovilar**

### CODE REVIEW

**Comment by iCHAIT** [comment]
@sergiovilar Don't you think gitup is better than tower?

**Comment by iCHAIT** [comment]
Moreover, GitUp is open source and also Mac exclusive!

**Comment by sergiovilar** [comment]
@iCHAIT I think that they are different things. Did you tried Tower? It's amazing :grinning:

Tower is also mac exclusive and is more like a "better" sourcetree, I think that is an alternative for who wants a paid app.

**Comment by iCHAIT** [comment]
Oh, actually I didn't get the opportunity to use tower, though from the outset it looked like it was similar to GitUp.

Nevertheless, I think you may want to remove `mac` from the description and this should be ready to go :)

**Comment by sergiovilar** [comment]
@iCHAIT done!

**Comment by iCHAIT** [comment]
Thanks :)

**Pull request merged**
