### PR TITLE
adds Radium (internet radio streaming client)

### PR DESCRIPTION
**Pull request by seisfeld**
Adds Radium. A quite nice menu bar streaming client for internet radio streams.

### CODE REVIEW

**Comment by aulizko** [comment]
I just have no words. 
Listen internet radio that is available for free within a program that costs money? You should be joking. 
You can listen radio with iTunes which is free. 
You can listen hand-picked radio with iTunes Music. That's not free, ok.
You can select between services like Spotify, Pandora, Rdio, Deezer with great algorithms that will throw new music at you based on what you like or not. They have free price plans with ads and premium without ads. 

And on top of that all you can listen any radio just inside your command line with `mplayer` in one command, like this:

```bash
$ mplayer -playlist <some url that ends with>.pls
```

or

```bash
$ mplayer <any other url>
```

or you can even play it at the background so you will have free console:

```bash
mplayer <opts> <url> </dev/null >/dev/null 2>&1 &
```
And all of it is free. I mean, really free.
You can choose any of thousands (literally: **thousands**) internet radio stations and play it inside of iTunes or Mplayer. Just try to google it. 
This is a good place of searching for a good internet radio station: http://www.xatworld.com/radio-search/

**Comment by seisfeld** [comment]
I'm sorry but what is this here? The Awesome OS X list or the Awesome OPEN SOURCE for OS X list? I did not contribute to this repo to get a lesson about free stuff. I make my code open source too but i accept there is software out there that costs money and if its good everyone should be free (haha pun intended!) to use it. Consider this one closed. I'm out.

**Comment by aulizko** [comment]
@seisfeld Don't be discouraged by my own (and only my own) disapproval. 
I do not have any authority inside this list, I've just said my own point of view. 
Would your PR be merged or not is completely not my desicion.

And I am sorry if I have said something bad. 
I just had a really, really bad day. Just had broken with my gf. 
Again, I am deeply sorry that I spoiled your day. I didn't mean it.

**Comment by herrbischoff** [comment]
Now, come on you both. Pull requests for this list are mere recommendations. At least that's my interpretation of my short time here.

@aulizko: Believe it or not, there are people who are happy to pay for a nice GUI wrapper to free command line tools. People who do not use the command line at all. Who do not like iTunes or any of the myriad of alternatives that surely exist. Strictly speaking, you could actually describe the whole OS X desktop experience as a glorified graphical wrapper to what's — at its core — open source software. Apart from that, it wouldn't hurt to keep critical comments neutral, focussing on the facts, without insulting the other. After all, GitHub is not 4chan.

@seisfeld: Don't feel discouraged by one angry comment. Don't run away with your tails between your legs. Coders are strange beings, as you probably know and often not well versed in the social graces. If you feel something should be on this list, just send a pull request, as you did. Ultimately, it's up to the maintainer to decide if it gets included or not — not some random person commenting in a rather aggressive tone.

I don't feel I should be any kind of conflict resolution person but having extensively contributed to this list and being a human being and all that, I strongly believe in open and factual discussing. That just came onto my mind when reading across this.

**Comment by aulizko** [comment]
@herrbischoff , @seisfeld 
You're right, and I'm not. 
Again, I am really sorry. I feel shame. 
I had not by any means have said what I've said. Or, at least, I shouldn't put it in this words. 
Sorry again.

**Comment by seisfeld** [comment]
@herrbischoff @aulizko Yeah probably a little over reacting on my side here as well. But I know these type of discussions about the right text editor, the right Linux distro so on and so forth. Life is too short for that haha 😉. Apologies accepted though.

**Comment by iCHAIT** [comment]
Completely agree with @herrbischoff .

It was a bit disheartening to see such kind of response from both of you @seisfeld  and @aulizko, I am sure that none of it was meant to disrespect anyone but still it was not required in the first place. 

@seisfeld I don't think their was any need to close the PR, you should have at least waited for my response, what if many other people use this tool and are quite happy with it, It is not about a single person admonishing your suggestion, you may have got  +1's from other fellow developers and users of the same application, and this could have got merged. It is a little sad to see such an attitude.

**Comment by iCHAIT** [comment]
And one thing I wanted to clear out, as many other developers has a doubt regarding the same.

The list is of course **Awesome OS X** and we want to have as much awesome tools as we can irrespective of the fact whether it is open source or not, being a  paid or a  free app does not by any means decides the fate of that app getting merged into this list, but it being really awesome does :)

I hope that this is fine with everyone!

**Comment by seisfeld** [comment]
Very good attitude @iCHAIT !

**Comment by aulizko** [comment]
@seisfeld Let's forget about this, ok? :)

@iCHAIT May I ask about unrelated topic? I think it would be good if I'll write a gist that describes how to do some CLI-doable jobs without any apps installed and send a PR so it'll be included somewhere below the list? 
I mean, tasks like "discover disk usage" can be done with one CLI command. Tasks like "clean deleted app garbage", "clean memory", "compress mail archive", "listen a radio/music", "show some reminders", "edit hosts file", "show/hide hidden files" - all of it and many more can be done with one and only one CLI command. No need to install any software (even with Homebrew), no need to pay any money. I think it would be interesting for people that have some interest into Mac OS X insides and for people that are interested in the console.

**Comment by iCHAIT** [comment]
@aulizko Sound good to me :+1: 

@herrbischoff  What are your thoughts?

**Comment by dufferzafar** [comment]
Um, @aulizko cli based quickies are a very good idea for a gist (or maybe even a complete repo) 

Not sure if that'd make sense in Awesome OSX, but definitely a great idea for a separate repo. 

Something similar (I guess) - https://github.com/jlevy/the-art-of-command-line

**Comment by herrbischoff** [comment]
@iCHAIT: Sounds to me like a candidate for a link in the Miscellaneous section. I like the idea. But how about @dufferzafar's idea of a separate repository? Something along the lines of "OS X command line quickies". @aulizko, you could build a README.md file in that repo, a snippet collection if you will. In any case, I would definitely keep it separate from Awesome OS X.

**Comment by aulizko** [comment]
@herrbischoff @iCHAIT Let's do this way: first, I'll try to implement it, then open a PR and we discuss it further. The thing is I myself do not know for now what would be result and how long it would be.

**Comment by iCHAIT** [comment]
@aulizko Fair enough, you can proceed with it, and as rightly pointed out by @herrbischoff we can definitely have a new sub category of `Command Line Utilities`

**Comment by herrbischoff** [comment]
@aulizko, @iCHAIT: Sounds good! I have some snippets of myself, including full-blown Oh My ZSH configurations with aliases and functions galore. I'm actually tempted to start an "Awesome OS X Command Line" repository. :)

**Comment by dufferzafar** [comment]
@herrbischoff @aulizko If you guys do decide to work on it, can you please keep the non-osx stuff separate? (like oh-my-zsh configs, commands that are available everywhere etc)

It'll help users like me, who are on Linux.

**Comment by seisfeld** [comment]
Recently I stumbled over this: https://github.com/mathiasbynens/dotfiles/blob/master/.osx

Contains tons of command line "hacks" for OS X.

**Comment by herrbischoff** [comment]
@dufferzafar: Done. And yes, this is entirely different. I believe discussions should take place in issues.

**Comment by seisfeld** [comment]
I resubmitted this PR under #137.

**Pull request closed without merging**
