### PR TITLE
Add SSH Tunnel Manager utility.

### PR DESCRIPTION
**Pull request by appleboy**
Link: http://projects.tynsoe.org/en/stm/index.php

cc @iCHAIT

### CODE REVIEW

**Comment by herrbischoff** [comment]
This looks like an *ancient* piece of software...

**Comment by appleboy** [comment]
@herrbischoff `SSH Tunnel Manager` is free software but [SSH Tunnel](http://codinn.com/products/ssh-tunnel/) is not free in `Utilities` section.

**Comment by herrbischoff** [comment]
That is not an argument. The question is whether it is and Awesome application or not. I certainly seems that it is not.

**Comment by appleboy** [comment]
@herrbischoff OK, agree with you.

**Pull request closed without merging**
