### PR TITLE
Webpage Development Thread

### PR DESCRIPTION
**Pull request by seanoh1989**
Hello all,

This is Sean, a college student in San Diego, California, USA. I'd like to make a front-end website for the awesome-osx. A short discussion has been made [here](https://github.com/iCHAIT/awesome-osx/issues/134). Please take a look before proceed.

##Welcome back

So my goal is to create a **pretty** front end website that can attract non-git users (everyday mac users from beginners to experts). To achieve that, I was thinking to create a website using *Bootstrap 3* (maybe will port to 4 when it comes out?). As I mentioned, it will look similar to my website's project section http://saehunseanoh.me/#projects .

Adding item will be as easy as filling out a premade form -> copy -> paste so people with no web development can still involve in this project.

However, @herrbischoff mentioned that he wants to keep the website look as simple as possible, so maybe just stick with the markdown format.

What do everybody think? 

This PR: removed README.md and contributing.md temporarily, added empty index.html file

### CODE REVIEW

**Comment by iCHAIT** [comment]
@seanoh1989 We need to see the code for the web page you are making, once you push the code for that, we can have a discussion on the code, design etc.

**Comment by seanoh1989** [comment]
@iCHAIT Okay. My work got super duper busy just now so I can't start until end of this month :cry: I'll update this as soon as possible. Thanks for waiting.

**Comment by iCHAIT** [comment]
@seanoh1989  Please close if you are not interested in continuing this.

**Comment by iCHAIT** [comment]
Let me know if you are interested in working on this and I'll reopen!

**Comment by seanoh1989** [comment]
Almost graduating (This June) and I will have time for this somehow LOL I'm
sincerely sorry though. I underestimated my time frame. I'll get back to
you!

**Pull request closed without merging**
