### PR TITLE
adds Radium (internet radio streaming client)

### PR DESCRIPTION
**Pull request by seisfeld**
Second attempt. :wink:

Adds Radium. A quite nice menu bar streaming client for internet radio streams.

### CODE REVIEW

**Comment by iCHAIT** [comment]
@seisfeld Sorry for not getting back to you earlier and thanks for opening a PR for this, Though I am dubious about this as I haven't used it, so lets see if it gets support from others. I hope you are fine with that :)

**Comment by iCHAIT** [comment]
aghast, looks like I cannot add a `Needs +1` label to this :/

**Comment by seisfeld** [comment]
I doubt it will get too much +1's ;) It's still awesome haha.

**Comment by iCHAIT** [comment]
Lets wait please don't close the PR :p

**Comment by iCHAIT** [comment]
And BTW just a couple of +1's would do!

**Comment by seisfeld** [comment]
Question is how large the audience is here to support this kind of voting. I stumbled over this more or less by "accident" myself. :)

**Comment by iCHAIT** [comment]
Well quite obviously there aren't many, but apparently there are more than 100 watchers for this repo, even if a couple of them can support this this would be worth it, otherwise I'll try and get my hands over it myself!

**Comment by seisfeld** [comment]
Someone considered to Look at this one to decide on a merge/no merge?

**Comment by seisfeld** [comment]
@iCHAIT Still no one interested to get this one added?

**Comment by herrbischoff** [comment]
Just my two cents: nope. It's too expensive and pointless for what it does. It's just a polished audio player. The same functionality can be achieved with any kind of audio application for free: VLC, Vox, mplayer, mpv, you name it — and that's just the GUI ones...

**Comment by seisfeld** [comment]
Okay. What is the process with this PR then? Will this stay open for eternity or will this be closed then?

**Comment by herrbischoff** [comment]
Since you opened it, you should be able to close it if you feel like it. Apart from this, @iCHAIT is the one who ultimately decides what happens if you leave it open. Your call.

**Comment by seisfeld** [comment]
Okay i'll wait for a final call then from @iCHAIT. In case of :-1: i'll close it.

**Comment by iCHAIT** [comment]
@seisfeld Okay, no +1's yet, and $10 seems expensive for what it does, I think you should close it.

**Comment by seisfeld** [comment]
Okay.

**Pull request closed without merging**
