### PR TITLE
Add a bunch of developer, backup, utility, and productivity applications

### PR DESCRIPTION
**Pull request by forgottenleaf**
* Add a backup category.

### CODE REVIEW

**Comment by forgottenleaf** [comment]
Looks like LICEcap was already added in PR #67, I apologize for duplicating.

**Comment by herrbischoff** [comment]
@forgottenleaf: In that case you should update your pull request. ;) And possibly considering using one PR for every application added. I know, I did the same with just bundling up a whole bunch of stuff. That was a bad idea. Makes merging after other updates a pain.

**Comment by iCHAIT** [comment]
@forgottenleaf @herrbischoff 

Yeah, I was about to mention that for both the PR's and maybe I'll add it to the contribution guidelines as well, it is better to make separate PR for each application as it will be easier to manage and review them.

**Comment by forgottenleaf** [comment]
@iCHAIT 

Well from what I saw the only conflict was with LICEcap, should I still go ahead and split this into individual PR's and make sure I have no conflicts, or should I only take this approach for future PR's?

**Comment by iCHAIT** [comment]
I think it is better to split them, it is not just about conflicts but it would be easier to review for everyone.

**Comment by sergiovilar** [comment]
@forgottenleaf split in smaller PRs makes @iCHAIT life's easier and also is what the contributions guidelines tells to do.

**Comment by herrbischoff** [comment]
@sergiovilar: Are you the dedicated contribution guideline watchdog? :P

**Comment by sergiovilar** [comment]
@herrbischoff I just don't think is fair some people follow guidelines and other people ignore.

**Comment by herrbischoff** [comment]
It should really be at the discretion of the project owner what to accept and what to reject. I see where you're coming from but whining about it never solved anything. Constantly contributing in the preferred way *demonstrates* others how to do it. Just look at the new PRs after I split my humongous PR.

**Comment by herrbischoff** [comment]
Please close and resubmit apps as single pull requests. Also, some applications you have submitted for the second or third time already in later pull requests. Please watch through your PR's an decide what is really worth it to be added instead of just dumping every second app you use. Thanks.

**Comment by iCHAIT** [comment]
@forgottenleaf  I am closing this for now, please review your suggestions against the list and submit each suggestion as a single PR.

**Pull request closed without merging**
