### PR TITLE
Adding Colloquy

### PR DESCRIPTION
**Pull request by rsiwady29**

### CODE REVIEW

**Comment by herrbischoff** [comment]
Does Colloquy still run on Yosemite? Also, please add the source code repository to the OSS icon. Thanks.

**Comment by rsiwady29** [comment]
Yes, currently using it on Yosemite. Source code repo added.

**Comment by herrbischoff** [comment]
Please also take care of the duplicates. And remember, one pull request per application. ;)

**Comment by rsiwady29** [comment]
@herrbischoff Updates done. Atom was messing around with some extra spaces.

**Comment by herrbischoff** [comment]
Looks good! Now it's up to @iCHAIT to decide and merge.

**Comment by iCHAIT** [comment]
Looks good to me but still you'd want it place it alphabetically @rsiwady29

**Comment by iCHAIT** [comment]
Colloquy is already on the list. Thanks.

**Pull request closed without merging**
