### PR TITLE
Added Clocker

### PR DESCRIPTION
**Pull request by Abhishaker17**
Added Clocker - An OSX menubar utility to keep track of your friends/colleagues in different time zones.

### CODE REVIEW

**Comment by iCHAIT** [comment]
I installed the application on my mac via the app store, when I open the application a "star icon" appears on my menu bar but when I click on that icon it sort of crashes (disappears from the menu bar) :\

**Comment by Abhishaker17** [comment]
I have added a new version under the Release tab at the following link:
https://github.com/Abhishaker17/Clocker

Can you try that? :100:

**Comment by iCHAIT** [comment]
Sure, will get back to you after testing it out :)

**Comment by iCHAIT** [comment]
@Abhishaker17  I installed it via the release from the repository, unfortunately I am still facing the same issue :(

> when I open the application a "star icon" appears on my menu bar but when I click on that icon it sort of crashes (disappears from the menu bar)

And nothing happens!

**Comment by Abhishaker17** [comment]
Apologies. The issue is with the locale. Have fixed it and currently testing it rigorously. Will post an update soon. Thanks. :)

**Comment by iCHAIT** [comment]
Oh, okay, just ping me when its ready :)

**Comment by Abhishaker17** [comment]
Hey,
Here is an updated and tested version of Clocker:
https://itunes.apple.com/us/app/clocker-menubar-world-clock/id1056643111?mt=12

Do let me know if you any queries. Thanks.

**Pull request merged**
