### PR TITLE
Add Telegram to Chat Clients

### PR DESCRIPTION
**Pull request by AnatoliyGatt**
Telegram - A messaging app with a focus on speed and security, it’s super fast, simple and free.

### CODE REVIEW

**Comment by vastus** [comment]
+1

**Comment by herrbischoff** [comment]
Please do not use App Store links. The correct link for this application would be `https://telegram.org`. Thanks.

**Comment by AnatoliyGatt** [comment]
@herrbischoff In #119 I was asked to replace app's homepage link with an App Store link. I guess the reason was that the app is not unique to OS X. So I'll keep it this way.

**Comment by herrbischoff** [comment]
Good point.

**Pull request merged**
