### PR TITLE
Add Awesome Command Line Apps

### PR DESCRIPTION
**Pull request by herrbischoff**
Shamelessly self-promoting my not-quite-finished-but-already-useful sister list to Awesome OS X Command Line.

### CODE REVIEW

**Comment by herrbischoff** [comment]
Just wanted to check again about the status of inclusion.

**Comment by iCHAIT** [comment]
Well, the [other list](https://github.com/aharris88/awesome-cli-apps) has been merged into the [awesome list](https://github.com/sindresorhus/awesome#development-environment) and as I mentioned in [this thread](https://github.com/iCHAIT/awesome-osx/pull/195) I believe we should have the one that got merged in the Awesome List. So maybe you can edit this PR to include that list, or close this.I hope you don't mind :)

**Comment by herrbischoff** [comment]
I mind just a little. It's too bad because I believe most of the tools on the other list are fancy NodeJS wrappers or rewrites for functionality that's long been present in Unix before the Hipster crowd showed up. The fact that after being merged in the Awesome List it has received max. ~100 stars speaks for itself. I'm not bitter, a bit disappointed maybe, since I strive for quality. I'm going to close this then.

**Comment by iCHAIT** [comment]
Fair enough!

Nevertheless, I honestly felt that **Awesome OS X Command Line** is in itself a great resource and the other list is not required as far as this particular list is concerned.

**Comment by herrbischoff** [comment]
Sounds about right. Good to hear that you like Awesome OS X Command Line. It was kind of an unexpected success. Must have hit a spot. ;)

**Pull request closed without merging**
