### PR TITLE
Add `Amphetamine` to Utilities

### PR DESCRIPTION
**Pull request by williamboman**
This app is so much better than Caffeine, I sorta want to remove Caffeine from the list tbh.

### CODE REVIEW

**Comment by iCHAIT** [comment]
@williamboman  Nice, we should have this on the list, but I am a bit reluctant in removing Caffeine from the list as it is really very popular among mac users, but on the same time it would also be redundant to have a couple of similar applications that serve exactly the same purpose in the list.

What do you think?

**Comment by williamboman** [comment]
Since it is an "awesome" list, I definitely think Caffeine should be replaced by Amphetamine.

**Comment by iCHAIT** [comment]
Hmm, fair enough, so you can remove Caffeine from this and after fixing the conflicts this should be ready to go :)

**Comment by iCHAIT** [comment]
@williamboman So can you remove caffeine and fix conflicts?

**Comment by williamboman** [comment]
@iCHAIT Done

**Pull request merged**
